// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_line_count
unsigned int get_line_count(std::string path, bool has_header, bool is_gzip_compressed);
RcppExport SEXP BGData_get_line_count(SEXP pathSEXP, SEXP has_headerSEXP, SEXP is_gzip_compressedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    Rcpp::traits::input_parameter< bool >::type has_header(has_headerSEXP);
    Rcpp::traits::input_parameter< bool >::type is_gzip_compressed(is_gzip_compressedSEXP);
    __result = Rcpp::wrap(get_line_count(path, has_header, is_gzip_compressed));
    return __result;
END_RCPP
}
