# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_line_count <- function(path, has_header, is_gzip_compressed) {
    .Call('BGData_get_line_count', PACKAGE = 'BGData', path, has_header, is_gzip_compressed)
}

get_file_header <- function(path, is_gzip_compressed) {
    .Call('BGData_get_file_header', PACKAGE = 'BGData', path, is_gzip_compressed)
}

